In [1]:
from glob import glob
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.nn.functional as F
from scipy.stats import ttest_ind

/home/mahirwar/miniconda3/envs/kfold_amy_plaque1/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/mahirwar/miniconda3/envs/kfold_amy_plaque1/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
csv_files  = glob(os.path.join("/gladstone/finkbeiner/steve/work/data/npsad_data/monika/Antibodies_detection/codes/crop_based/seg_results/","*.csv"))
pd.read_csv(csv_files[0]).head(2)

,Unnamed: 0,slide_id,img_name,area,perimeter,eccentricity,major_axis_length,minor_axis_length,solidity,extent,aspect_ratio,circularity,bbox_xmin,bbox_xmax,bbox_ymin,bbox_ymax,centroid_x,centroid_y,label,class
0,0,PD158_C110-115_EntCx David Menassa.svs,PD158_C110-115_EntCx David Menassa.svs/69627x_...,201,56.870058,0.780396,21.009171,13.136720,0.881579,0.628125,1.599271,0.780978,719,739,570,586,729.442786,578.711443,1,2
1,1,PD158_C110-115_EntCx David Menassa.svs,PD158_C110-115_EntCx David Menassa.svs/69627x_...,34,21.278175,0.890169,10.085081,4.595071,0.871795,0.618182,2.194760,0.943670,992,1003,762,767,997.735294,763.558824,2,2

In [4]:
df_list =  []
for i in range(len(csv_files)):
    grp_by_class= pd.read_csv(csv_files[i]).groupby(["slide_id","class"]).agg({"area":["mean","std"],"perimeter":["mean","std"],"eccentricity":["mean","std"],
                                                                "major_axis_length":["mean","std"],"minor_axis_length":["mean","std"],
                                                                "solidity":["mean","std"],"extent":["mean","std"],"aspect_ratio":["mean","std"],
                                                                "circularity":["mean","std"], "img_name":["count"]})
    grp_by_class.columns = ["area_mean",'area_std','perimeter_mean','perimeter_std','eccentricity_mean',
                  'eccentricity_std',  'major_axis_length_mean', 'major_axis_length_std', 'minor_axis_length_mean',
                  'minor_axis_length_std','solidity_mean', 'solidity_std', 'extent_mean',  'extent_std', 'aspect_ratio_mean',
                  'aspect_ratio_std', 'circularity_mean', 'circularity_std', "lb_count"]
    
    grp_by_class = grp_by_class.reset_index()
    grp_by_slide = pd.pivot(grp_by_class, columns =  ["class"], index="slide_id")
    col_names = []
    mapping = {1:"mature_lb",2:"pre_lb",3:"neg_lb"}
    for column in grp_by_slide.columns:
        col_names.append(column[0]+"_"+mapping[column[1]])
    grp_by_slide.columns = col_names
    grp_by_slide= grp_by_slide.reset_index()
    df_list.append(grp_by_slide)

In [5]:
all_df_features  =  pd.concat(df_list)

In [6]:
oxford_data = pd.read_csv("/gladstone/finkbeiner/steve/work/data/npsad_data/monika/Antibodies_detection/codes/prov-gigapath/data/antibodies_data/data_imperial2.csv")

In [7]:
oxford_data_feat =  pd.merge(oxford_data,all_df_features, on="slide_id", how="left")

In [8]:
oxford_data_feat.head(2)

,slide_id,brain_region,pat_id,anitibody,LBD_flag,label,Brain_bank,area_mean_mature_lb,area_mean_pre_lb,area_mean_neg_lb,...,aspect_ratio_std_neg_lb,circularity_mean_mature_lb,circularity_mean_pre_lb,circularity_mean_neg_lb,circularity_std_mature_lb,circularity_std_pre_lb,circularity_std_neg_lb,lb_count_mature_lb,lb_count_pre_lb,lb_count_neg_lb
0,PD134-DLB--Amygdala-C110-115.svs,Amygdala,PD134,C110-115,DLB,1,Oxford,547.247741,235.936411,359.281426,...,1.058582,1.008514,1.152042,1.016600,2.588069,2.857844,2.082594,18261.0,17393.0,18154.0
1,PD134-DLB--EntCx-C110-115.svs,EntCx,PD134,C110-115,DLB,1,Oxford,476.007864,220.410873,432.484103,...,1.076915,1.054892,1.157449,1.033833,2.769480,2.948588,2.273730,10427.0,14384.0,14846.0

In [9]:
oxford_data_feat.columns

Index(['slide_id', 'brain_region', 'pat_id', 'anitibody', 'LBD_flag', 'label',
       'Brain_bank', 'area_mean_mature_lb', 'area_mean_pre_lb',
       'area_mean_neg_lb', 'area_std_mature_lb', 'area_std_pre_lb',
       'area_std_neg_lb', 'perimeter_mean_mature_lb', 'perimeter_mean_pre_lb',
       'perimeter_mean_neg_lb', 'perimeter_std_mature_lb',
       'perimeter_std_pre_lb', 'perimeter_std_neg_lb',
       'eccentricity_mean_mature_lb', 'eccentricity_mean_pre_lb',
       'eccentricity_mean_neg_lb', 'eccentricity_std_mature_lb',
       'eccentricity_std_pre_lb', 'eccentricity_std_neg_lb',
       'major_axis_length_mean_mature_lb', 'major_axis_length_mean_pre_lb',
       'major_axis_length_mean_neg_lb', 'major_axis_length_std_mature_lb',
       'major_axis_length_std_pre_lb', 'major_axis_length_std_neg_lb',
       'minor_axis_length_mean_mature_lb', 'minor_axis_length_mean_pre_lb',
       'minor_axis_length_mean_neg_lb', 'minor_axis_length_std_mature_lb',
       'minor_axis_length_std_pre_lb', 'minor_axis_length_std_neg_lb',
       'solidity_mean_mature_lb', 'solidity_mean_pre_lb',
       'solidity_mean_neg_lb', 'solidity_std_mature_lb', 'solidity_std_pre_lb',
       'solidity_std_neg_lb', 'extent_mean_mature_lb', 'extent_mean_pre_lb',
       'extent_mean_neg_lb', 'extent_std_mature_lb', 'extent_std_pre_lb',
       'extent_std_neg_lb', 'aspect_ratio_mean_mature_lb',
       'aspect_ratio_mean_pre_lb', 'aspect_ratio_mean_neg_lb',
       'aspect_ratio_std_mature_lb', 'aspect_ratio_std_pre_lb',
       'aspect_ratio_std_neg_lb', 'circularity_mean_mature_lb',
       'circularity_mean_pre_lb', 'circularity_mean_neg_lb',
       'circularity_std_mature_lb', 'circularity_std_pre_lb',
       'circularity_std_neg_lb', 'lb_count_mature_lb', 'lb_count_pre_lb',
       'lb_count_neg_lb'],
      dtype='object')

In [10]:
oxford_data_feat["LBD_flag"].value_counts()

LBD_flag
DLB    34
PDD    34
Name: count, dtype: int64

In [11]:
oxford_data_feat.groupby(["LBD_flag"])["lb_count_mature_lb"].mean()

LBD_flag
DLB    17767.382353
PDD     9540.424242
Name: lb_count_mature_lb, dtype: float64

In [12]:
oxford_data_feat.groupby(["LBD_flag"])["lb_count_pre_lb"].mean()

LBD_flag
DLB    13847.500000
PDD    19744.969697
Name: lb_count_pre_lb, dtype: float64

In [13]:
oxford_data_feat.groupby(["LBD_flag"])["lb_count_neg_lb"].mean()

LBD_flag
DLB    12555.529412
PDD    20181.969697
Name: lb_count_neg_lb, dtype: float64

In [14]:
oxford_data_feat.groupby(["LBD_flag"])["area_mean_mature_lb"].mean()

LBD_flag
DLB    482.588585
PDD    510.393066
Name: area_mean_mature_lb, dtype: float64

In [15]:
oxford_data_feat.groupby(["LBD_flag"])["circularity_mean_mature_lb"].mean()

LBD_flag
DLB    1.048320
PDD    1.041182
Name: circularity_mean_mature_lb, dtype: float64

In [16]:
oxford_data_feat.groupby(["LBD_flag"])["eccentricity_mean_mature_lb"].mean()

LBD_flag
DLB    0.735752
PDD    0.753425
Name: eccentricity_mean_mature_lb, dtype: float64

In [17]:
oxford_data_feat.groupby(["LBD_flag",'brain_region'])["lb_count_mature_lb"].mean()

LBD_flag  brain_region
DLB       Amygdala        26071.750000
          EntCx           13140.214286
          Striatum        13408.375000
PDD       Amygdala        11826.705882
          EntCx            6328.461538
          Striatum        10503.333333
Name: lb_count_mature_lb, dtype: float64

In [18]:
oxford_data_feat.groupby(["LBD_flag",'anitibody'])["lb_count_mature_lb"].mean()

LBD_flag  anitibody
DLB       C110-115     18728.214286
          C34-45       17094.800000
PDD       C110-115      6980.391304
          C34-45       15428.500000
Name: lb_count_mature_lb, dtype: float64

In [20]:
oxford_data_feat.to_csv("/gladstone/finkbeiner/steve/work/data/npsad_data/monika/Antibodies_detection/codes/crop_based/analysis/slide_features.csv")

In [37]:
columns_to_vis = oxford_data_feat.columns[7:].values

In [47]:
imp= []
for col in columns_to_vis:
    print(oxford_data_feat.groupby(["LBD_flag"])[col].mean())
    res= ttest_ind(oxford_data_feat[oxford_data_feat["LBD_flag"]=="PDD"][col].values, oxford_data_feat[oxford_data_feat["LBD_flag"]=="DLB"][col].values,nan_policy='omit')
    print(res)
    if res.pvalue<0.05:
        imp.append(col)

LBD_flag
DLB    482.588585
PDD    510.393066
Name: area_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=0.6034107120436962, pvalue=0.5483354352003176)
LBD_flag
DLB    189.351592
PDD    188.737810
Name: area_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=-0.08413852901090131, pvalue=0.9332048936523412)
LBD_flag
DLB    3691.354405
PDD    7714.417578
Name: area_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=1.671555259501149, pvalue=0.0994200557915516)
LBD_flag
DLB    601.664016
PDD    724.082278
Name: area_std_mature_lb, dtype: float64
Ttest_indResult(statistic=1.2989389711438102, pvalue=0.1985538721158314)
LBD_flag
DLB    212.015844
PDD    192.831587
Name: area_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-3.514815358379338, pvalue=0.0008070882176456953)
LBD_flag
DLB    17619.895592
PDD    39815.098439
Name: area_std_neg_lb, dtype: float64
Ttest_indResult(statistic=2.09228948255126, pvalue=0.040322195469026094)
LBD_flag
DLB    79.695205
PDD    89.517914
Name: perimeter_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=1.2461973524921677, pvalue=0.2171647340698785)
LBD_flag
DLB    46.193517
PDD    47.787554
Name: perimeter_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=1.3713999712017888, pvalue=0.17496620085049272)
LBD_flag
DLB    103.252048
PDD    153.258321
Name: perimeter_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=1.8176386197995578, pvalue=0.07372849086335681)
LBD_flag
DLB     71.054931
PDD    101.303188
Name: perimeter_std_mature_lb, dtype: float64
Ttest_indResult(statistic=1.5711238423137335, pvalue=0.12100939771657816)
LBD_flag
DLB    33.187063
PDD    31.895732
Name: perimeter_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-2.439472764727543, pvalue=0.017446833469753384)
LBD_flag
DLB    244.823387
PDD    421.646039
Name: perimeter_std_neg_lb, dtype: float64
Ttest_indResult(statistic=1.8600924214761891, pvalue=0.0673979277852388)
LBD_flag
DLB    0.735752
PDD    0.753425
Name: eccentricity_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=4.243356668508906, pvalue=7.13417920319468e-05)
LBD_flag
DLB    0.734343
PDD    0.745371
Name: eccentricity_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=5.360802562695729, pvalue=1.173044475412224e-06)
LBD_flag
DLB    0.720732
PDD    0.714125
Name: eccentricity_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=-1.7610668590818523, pvalue=0.08293031591685149)
LBD_flag
DLB    0.215000
PDD    0.215195
Name: eccentricity_std_mature_lb, dtype: float64
Ttest_indResult(statistic=0.11135452164344403, pvalue=0.9116783651111717)
LBD_flag
DLB    0.223343
PDD    0.213353
Name: eccentricity_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-4.601175645177022, pvalue=2.0000322595427606e-05)
LBD_flag
DLB    0.213358
PDD    0.211442
Name: eccentricity_std_neg_lb, dtype: float64
Ttest_indResult(statistic=-0.966081129681539, pvalue=0.337584364125328)
LBD_flag
DLB    28.798288
PDD    35.281653
Name: major_axis_length_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=1.5108447301633892, pvalue=0.13567452349858825)
LBD_flag
DLB    17.701515
PDD    18.447881
Name: major_axis_length_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=1.8982336312331871, pvalue=0.062106874457686166)
LBD_flag
DLB    35.809398
PDD    45.236015
Name: major_axis_length_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=1.2936290068846492, pvalue=0.20037178173834902)
LBD_flag
DLB    24.855258
PDD    44.720930
Name: major_axis_length_std_mature_lb, dtype: float64
Ttest_indResult(statistic=1.7067764048392602, pvalue=0.09263713996617078)
LBD_flag
DLB    11.709917
PDD    11.790124
Name: major_axis_length_std_pre_lb, dtype: float64
Ttest_indResult(statistic=0.43041713523166086, pvalue=0.6683160428377111)
LBD_flag
DLB    74.293575
PDD    96.876177
Name: major_axis_length_std_neg_lb, dtype: float64
Ttest_indResult(statistic=1.0149929727186333, pvalue=0.3138724826897746)
LBD_flag
DLB    16.773580
PDD    15.979216
Name: minor_axis_length_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=-1.631010413321172, pvalue=0.10772452645869804)
LBD_flag
DLB    10.399304
PDD    10.487285
Name: minor_axis_length_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=0.3357211078383787, pvalue=0.7381624319932854)
LBD_flag
DLB    17.730355
PDD    25.596118
Name: minor_axis_length_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=2.3290326456197707, pvalue=0.022976850962503667)
LBD_flag
DLB    13.417699
PDD    13.351448
Name: minor_axis_length_std_mature_lb, dtype: float64
Ttest_indResult(statistic=-0.13556311323463827, pvalue=0.892585619214493)
LBD_flag
DLB    7.514990
PDD    6.848046
Name: minor_axis_length_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-6.039949195649303, pvalue=8.265475600891256e-08)
LBD_flag
DLB    28.607856
PDD    54.446701
Name: minor_axis_length_std_neg_lb, dtype: float64
Ttest_indResult(statistic=2.28963525925197, pvalue=0.025298149663297943)
LBD_flag
DLB    0.890136
PDD    0.885510
Name: solidity_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=-3.151591231186123, pvalue=0.002456022956442473)
LBD_flag
DLB    0.910170
PDD    0.908923
Name: solidity_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=-1.747737174746507, pvalue=0.08523190786182935)
LBD_flag
DLB    0.912723
PDD    0.910084
Name: solidity_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=-2.2020933724352934, pvalue=0.03121258706044483)
LBD_flag
DLB    0.098569
PDD    0.101567
Name: solidity_std_mature_lb, dtype: float64
Ttest_indResult(statistic=1.6008648286031786, pvalue=0.1142563367675501)
LBD_flag
DLB    0.073403
PDD    0.071157
Name: solidity_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-2.5382927452157893, pvalue=0.013544540458220532)
LBD_flag
DLB    0.069920
PDD    0.076538
Name: solidity_std_neg_lb, dtype: float64
Ttest_indResult(statistic=4.879776197835877, pvalue=7.20700058408031e-06)
LBD_flag
DLB    0.657512
PDD    0.663703
Name: extent_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=1.977391379038963, pvalue=0.05224105184297085)
LBD_flag
DLB    0.679477
PDD    0.670769
Name: extent_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=-5.095404308115252, pvalue=3.2184999721540174e-06)
LBD_flag
DLB    0.673811
PDD    0.670094
Name: extent_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=-1.814409326102399, pvalue=0.07422975530153)
LBD_flag
DLB    0.144919
PDD    0.154388
Name: extent_std_mature_lb, dtype: float64
Ttest_indResult(statistic=4.365869670825135, pvalue=4.6403853008994985e-05)
LBD_flag
DLB    0.138873
PDD    0.134729
Name: extent_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-4.503915283943047, pvalue=2.83895037205743e-05)
LBD_flag
DLB    0.130346
PDD    0.132824
Name: extent_std_neg_lb, dtype: float64
Ttest_indResult(statistic=1.5995699226871458, pvalue=0.1145439064353725)
LBD_flag
DLB    1.965265
PDD    3.412995
Name: aspect_ratio_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=2.6223191433290585, pvalue=0.010867090087861617)
LBD_flag
DLB    1.830514
PDD    1.881161
Name: aspect_ratio_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=4.674426405182044, pvalue=1.5330022964224734e-05)
LBD_flag
DLB    1.791453
PDD    1.852767
Name: aspect_ratio_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=0.9996374106320721, pvalue=0.32119294246637575)
LBD_flag
DLB    2.04895
PDD    7.09110
Name: aspect_ratio_std_mature_lb, dtype: float64
Ttest_indResult(statistic=2.700666844735278, pvalue=0.008813934386899204)
LBD_flag
DLB    1.178704
PDD    1.146042
Name: aspect_ratio_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-1.6446262685469724, pvalue=0.10487514308451218)
LBD_flag
DLB    1.230445
PDD    1.921167
Name: aspect_ratio_std_neg_lb, dtype: float64
Ttest_indResult(statistic=1.7847678332514232, pvalue=0.0789652819316042)
LBD_flag
DLB    1.048320
PDD    1.041182
Name: circularity_mean_mature_lb, dtype: float64
Ttest_indResult(statistic=-0.40754055069603307, pvalue=0.6849501734553536)
LBD_flag
DLB    1.175502
PDD    1.081065
Name: circularity_mean_pre_lb, dtype: float64
Ttest_indResult(statistic=-6.158626665423659, pvalue=5.1565037085613896e-08)
LBD_flag
DLB    1.054412
PDD    1.008368
Name: circularity_mean_neg_lb, dtype: float64
Ttest_indResult(statistic=-2.6387567287935423, pvalue=0.010403335878471455)
LBD_flag
DLB    2.733919
PDD    2.800243
Name: circularity_std_mature_lb, dtype: float64
Ttest_indResult(statistic=1.0196956764531826, pvalue=0.3116532008903127)
LBD_flag
DLB    2.898753
PDD    2.451147
Name: circularity_std_pre_lb, dtype: float64
Ttest_indResult(statistic=-6.577514371678717, pvalue=9.610029080825201e-09)
LBD_flag
DLB    2.324352
PDD    2.199743
Name: circularity_std_neg_lb, dtype: float64
Ttest_indResult(statistic=-1.6829815408040876, pvalue=0.09717646540405073)
LBD_flag
DLB    17767.382353
PDD     9540.424242
Name: lb_count_mature_lb, dtype: float64
Ttest_indResult(statistic=-2.639094164220652, pvalue=0.010394007397597044)
LBD_flag
DLB    13847.500000
PDD    19744.969697
Name: lb_count_pre_lb, dtype: float64
Ttest_indResult(statistic=3.1874237031151225, pvalue=0.0022076603522512566)
LBD_flag
DLB    12555.529412
PDD    20181.969697
Name: lb_count_neg_lb, dtype: float64
Ttest_indResult(statistic=1.8851264734010633, pvalue=0.06388406103946377)

In [48]:
imp

['area_std_pre_lb',
 'area_std_neg_lb',
 'perimeter_std_pre_lb',
 'eccentricity_mean_mature_lb',
 'eccentricity_mean_pre_lb',
 'eccentricity_std_pre_lb',
 'minor_axis_length_mean_neg_lb',
 'minor_axis_length_std_pre_lb',
 'minor_axis_length_std_neg_lb',
 'solidity_mean_mature_lb',
 'solidity_mean_neg_lb',
 'solidity_std_pre_lb',
 'solidity_std_neg_lb',
 'extent_mean_pre_lb',
 'extent_std_mature_lb',
 'extent_std_pre_lb',
 'aspect_ratio_mean_mature_lb',
 'aspect_ratio_mean_pre_lb',
 'aspect_ratio_std_mature_lb',
 'circularity_mean_pre_lb',
 'circularity_mean_neg_lb',
 'circularity_std_pre_lb',
 'lb_count_mature_lb',
 'lb_count_pre_lb']